steps:
- name: 'node:22'
  entrypoint: 'npm'
  args: ['ci']
  dir: 'website'
- name: 'node:22'
  entrypoint: 'npm'
  args: ['run', 'build']
  dir: 'website'
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'rsync', '-d', '-r', 'build/website', 'gs://${_BUCKET_NAME}']
