name: Build the Main Website
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Submit Build to Cloud Build
      uses: google-github-actions/submit-build@v1
      with:
        config: cloudbuild.yaml
        substitutions: _BUCKET_NAME=${{ vars.GCS_BUCKET_NAME }}
