# the machine should have the repo on the home
name: Deploy the Nginx
on:
  push:
    branches:
      - "master"
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: delete old deploys
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          rm -f /etc/nginx/sites-available/*
          rm -f /etc/nginx/sites-enabled/*

    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "reverse-proxy/*.dev"
        target: "/etc/nginx/sites-available/"
        # strip_components: 1

    - name: create symlinks
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          for file in `ls /etc/nginx/sites-available/*.dev`; do echo "creating the symbolic link of $file"; ln -s /etc/nginx/sites-available/$file /etc/nginx/sites-enabled/$file;done
