# the machine should have the repo on the home
name: remote ssh command
on:
  push:
    - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: multiple command
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/vitor_ecomp/nobuffer-site
          git pull --rebase