# the machine should have the repo on the home
name: Deploy the Nginx
on:
  push:
    branches:
      - "master"
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: multiple command
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          mkdir -p ${{ secrets.HOME_PATH }}/exec-logs
          cd ${{ secrets.HOME_PATH }}/workspace/nobuffer-site
          git reset --hard
          git checkout master
          git pull --rebase
          cd reverse-proxy
          sh deploy.sh >> ${{ secrets.HOME_PATH }}/exec-logs/`date +"%Y-%m-%d_%H:%M:%S"`.txt
